#!/bin/sh
rsync -av ./ u96511042@access773537801.webspace-data.io:~/cv --include=public/bundles --include=public/.htaccess --exclude-from=.gitignore --exclude=".*"
ssh u96511042@access773537801.webspace-data.io 'cd ~/cv && /usr/bin/php7.3-cli bin/console cache:clear'