easy_admin:
  entities:
    About:
      class: App\Entity\About
#      appel du template custom_edit.html.twig pour ajouter le script js algolia place
      templates:
        edit: 'admin/custom_edit.html.twig'
      label: 'Moi'
      disabled_actions: ['new', 'search', 'delete']
      list:
        fields:
          - { property: 'name', label: 'Nom et prénom' }
          - { property: 'email', label: 'Votre email' }
          #                    -{ property: 'image', label: 'Votre photo', type: 'image', base_path: '/assets/images/' }
          - { property: 'image', label: 'Votre photo', type: 'image', base_path: '%app.path.images%'  }
          - { property: 'job', label: 'Votre poste actuel' }
          - { property: 'address', label: 'Votre adresse' }
          - { property: 'cv', template: 'cv.html.twig', base_path: '%app.path.cv_doc%' }
          - { property: 'unsplashBgImage', label: 'Catégorie(s) d''image unsplash' }
          - { property: 'myBgImage', label: 'Votre photo d''arrière plan', type: 'image', base_path: '%app.path.images%'  }
      form:  # <-- 'form' is applied to both 'new' and 'edit' views
        fields:
          - { property: 'name', label: 'Nom et prénom' }
          - { property: 'email', label: 'Votre email', type: 'email' }
          - { property: 'job', label: 'Votre poste actuel' }
          - { property: 'address', label: 'Votre adresse' }
          - { property: 'lat', type: 'hidden' }
          - { property: 'lng', type: 'hidden' }
          #                    - { property: 'image', label: 'Votre photo', type: 'file_upload', type_options: { upload_dir: 'public/assets/images/', upload_filename: '[slug].[extension]' } }
          - { property: 'imageFile', label: 'Votre photo', type: 'vich_image', type_options: { allow_delete: true } }
          - { property: 'cvFile', label: 'Votre cv', type: 'vich_file', type_options: { allow_delete: false } }
          - { property: 'unsplashBgImage',
              label: 'Catégorie(s) d''image unsplash',
              help: 'Choisir une ou des catégories d''images <a href="https://unsplash.com/" target="_blank"> unslpash</a> ex: beach,france<br/>Mettre une virgule entre les valeurs.' }
          - { property: 'myBgImageFile', label: 'Votre photo d''arrière plan', type: 'vich_image', type_options: { allow_delete: true } }
