easy_admin:
  entities:
    # List the entity class name you want to manage
    Experience:
      class: App\Entity\Experience
      label: 'Expériences pro'
      list:
        fields:
          - { property: 'id' }
          - { property: 'business', label: 'Entreprise' }
          - { property: 'job', label: 'Emploi' }
          - { property: 'date', label: 'Date' }
          - { property: 'task', label: 'Tâche' }
          - { property: 'link', label: 'Site web' }
      form:
        fields:
          - { property: 'business', label: 'Entreprise' }
          - { property: 'job', label: 'Emploi' }
          - { property: 'date', label: 'Date' }
          - { property: 'task', label: 'Tâche', type: 'text_editor' }
          - { property: 'link', label: 'Site web' }
