easy_admin:
  entities:
    Footer:
      class: App\Entity\Footer
      label: 'Liens footer'
      list:
        fields:
          - { property: 'link', label: 'Lien' }
          - { property: 'icon', label: 'Icône', type: 'raw', css_class: icon_style }
      form:  # <-- 'form' is applied to both 'new' and 'edit' views
        fields:
          - { property: 'link', label: 'Lien' }
          - { property: 'icon', label: 'Icône', help: 'Ajouter une icône Fontawesome, avec la balise HTML i.' }
